### ISSUE TITLE
Save option is not working

### ISSUE THREAD

**Issue by karthik-msys** [dkmstr/openuds#14]
Hi Team ,
When we create a new record for **OsManager** save option is not working. when we run inside src folder **python manage.py shell** import the OsManager model and run the command  **obj = OSManager.objects.create(name='test')** it says **True** but not save new record in **uds_osmanager** in **mysql table**.but i insert the data directly using insert command and  **python manage.py shell** i run the command **OSManager.objects.filter(id=1).update(name='test1')** its **updated** the record. Could you please help on this issue.

**Comment by dkmstr** [comment]
Hi,
What means this? : OSManager.objects.create(name='test')  it says True.
This should not return true, but an object as in this:
In [2]: o = OSManager.objects.create(name='borrar')

In [3]: o
Out[3]: <OSManager: borrar of type  (id:14)>


It's something related to your DJANGO version or being missing something probably.
What version of DJANGO are you using?

And What version of UDS?

Can you check "log/uds.log" to see what is going on?

Have yo tried to insert it from UDS Dashboard?

You should use Django 1.9.9 for UDS 2.2 (current stable).
For UDS Master, we are currently working with Django 1.11

Best Regard,

Adolfo Gómez.

P.D. By the way, that kind of "empty register" is not contempled on UDS. You can create it for testing but do not keep it after that ;-).

By the way, the two clauses does not work the same on DJANGO. Firt clause, creates an object and saves is to database, returning the object itselft.
The second, creates an "UPDATE " clause from SQL, without loading the object into memory. So they are different cases...
Also, DJANGO uses a "copy" of the database, if you use a "test environment", so be care with this also.

**Comment by karthik-msys** [comment]
Thanks for your help and it seem the issue with 2.1 version after we used 2.2 the issue was resolved.
