### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by ahmedkaballo** [dkmstr/openuds#23]
what is the default username and password for the uds 2.1 version?
when i installed uds 2.1 it asks for login with username and password but you didn't mention any username and password.

**Comment by dkmstr** [comment]
take a look at https://github.com/dkmstr/openuds/blob/master/server/src/uds/core/util/Config.py#L253
These are "default" values, ensure to change them (on DB, using dashboard or API).

**Comment by harigist** [comment]
This worked : SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

Thanks @dkmstr
