### ISSUE TITLE
blank page 

### ISSUE THREAD

**Issue by ahmedkaballo** [dkmstr/openuds#24]
when i login to uds it gives me only the menu in the left side. but when i click on any  item on the menu(i.e services) it gives me a blank page.
![capture](https://user-images.githubusercontent.com/19692038/45667435-6c477900-bb19-11e8-8e86-6da1b7e1fb77.PNG)
![capture2](https://user-images.githubusercontent.com/19692038/45667708-977e9800-bb1a-11e8-8059-6265c200cb88.PNG)

**Comment by dkmstr** [comment]
As i told, try to look for requests/responses on the browser to see if there is something missing.
Press F12, and look at the "network" tab on firefox for example.

**Comment by ahmedkaballo** [comment]
when i open firefox and press F12 on the network section i get the following erroe 
![capture3](https://user-images.githubusercontent.com/19692038/45927118-88d71d00-bf2e-11e8-8edc-2b357277a612.PNG)

**Comment by ahmedkaballo** [comment]
when i traced the error i got the following 
![capture4](https://user-images.githubusercontent.com/19692038/45946227-981e9f00-bff0-11e8-8f18-954793dd645f.PNG)
i searched the  table in the database but i couldn't found it

**Comment by dkmstr** [comment]
mmm.  Seems that the cache table is not generated (its not in fact part of uds, but part of django itself.
The cache table must be created apart of UDS, so try running this: 
"python manage.py createcachetable"
And try again ;-)

**Comment by boguest** [comment]
I tried that, and am still getting a blank page. Here are the errors I get when I press F12:

![image](https://user-images.githubusercontent.com/10507621/45961558-ca2e0200-bfec-11e8-9f7b-5eb7fe36d513.png)

**Comment by dkmstr** [comment]
Seems that the .js are not being generated, probably coffescript is not installed, and it's used by UDS to translate to .js.
Please, take a look "inside" one of that requests, i mean, look what the server is returning.. I think that it's not the expected "compiled" js.... 
Ensure that you have "cofeescript installed. Take a look at the file "setting.py", search coffe and configure your cofeescript loation

I think that with this, all should run

**Comment by boguest** [comment]
I installed coffeescript, but still a no go.

Here is what the response is on the server when I try to enter the different pages:
![image](https://user-images.githubusercontent.com/10507621/46092432-df3c9980-c182-11e8-8e9c-e7f44178b5f8.png)


Please advise!

Thank you!

**Comment by dkmstr** [comment]
code 304 marked in blue is "not modified", but i can see that the pages "gui-......js" has a length of 13 bytes, what is wrong. (those javascript are a lot more bigger).

Try to see what a request to one of the "gui-d-...js" returns on the browser (look the request, and copy it to url, or look from "network" tab on F12 the response), probably it will give us some clue (i think again that is something related to coffescript. Look on "server/settings.py" and change the location of coffescript if needed)

**Comment by ahmedkaballo** [comment]
Hello 
Thanks for your support. now the broker runs very well.
but we noticed that the broker doesn't include an active directory authenticater, is it a feature for the enterprise version  only?

**Comment by dkmstr** [comment]
Yes, it is only an enterprise only feature, i mean, we haven't released the code for a few elements, and that is one of them.
