### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by boguest** [dkmstr/openuds#26]
Hello,

I installed all of the dependencies, followed the installation guide to the end, and ran the command "python manage.py migrate", which was successful. What do I do now? What are the next steps to get this up and running where I can browse to this uds server through my web browser?

Thank you,

Tim

**Comment by dkmstr** [comment]
you should run uds behind an apache (UDS uses Django as framework), but you can test it running "python manage.py runserver 0.0.0.0:8000" to make it listen on port 8000 and try it.
Also, you will have to run backend with "python manage.py taskManager --start"
