### ISSUE TITLE
Services are not published

### ISSUE THREAD

**Issue by harigist** [dkmstr/openuds#29]
Hi @dkmstr ,

I configured the service and imported the VM from my ovirt and created a base service

![1](https://user-images.githubusercontent.com/35326779/48410720-79719480-e765-11e8-8f55-717994631337.png)

Created an OS manager with Linux 

![2](https://user-images.githubusercontent.com/35326779/48411039-6a3f1680-e766-11e8-89ee-bcb9163024c1.png)

Created a service pool for this service

![3](https://user-images.githubusercontent.com/35326779/48411183-d1f56180-e766-11e8-8ddf-dce16930e978.png)

THis is the pool setting I added
 
![5](https://user-images.githubusercontent.com/35326779/48411220-eb96a900-e766-11e8-9eaf-2ada629d7459.png)

But the service pool is there in publication state for a long time

![4](https://user-images.githubusercontent.com/35326779/48411297-2c8ebd80-e767-11e8-81e2-a63044d7733a.png)

Could you help me why it is not stuck with the 'waiting for publication' state?

**Comment by harigist** [comment]
@dkmstr Do you need any other information, Please let me know.

**Comment by dkmstr** [comment]
Yes, you also need to run the "backend" part :)
try "python manage.py taskManager --start"
you can stop it with "python manage.py taskManager --stop"

That should work

**Comment by harigist** [comment]
Awesome @dkmstr  It worked :+1:
