### ISSUE TITLE
Rest API for openuds

### ISSUE THREAD

**Issue by harigist** [dkmstr/openuds#30]
Hi @dkmstr,

I am planning to automate the creation of service, service pool, OS manager creation etc.,
so could you please provide the REST API documentation for openuds, so it is easy for me to automate it. 

Thanks,
Harry

**Comment by dkmstr** [comment]
Sorry, this part is on the "TODO", it's an ardous work, and have no time for this right now :(
Maybe in a near future i could create it, but right now, it's impossible for me to take time into it :(.

**Comment by harigist** [comment]
Okay @dkmstr, Any alternative ways you can think of 
   i) to automate the creation of service, service pool, OS manager creation etc
  ii) Is there a document for How to use the VDI via UDS?
  iii) I see only the Memory can be configured via UDS, Is there a way to configure the disk size and CPU using UDS?

Thanks and Much Appreciated

**Comment by harigist** [comment]
@dkmstr  Also, I see few list of python file which says about Rest API's : https://github.com/dkmstr/openuds/tree/master/server/samples Any idea on these?

**Comment by dkmstr** [comment]
These are old, possible outdated REST api samples, buy maybe a good start :).
