### ISSUE TITLE
How to take remote desktop via Open UDS 

### ISSUE THREAD

**Issue by harigist** [dkmstr/openuds#31]
Hi @dkmstr ,

How to take remote desktop via Open UDS? 
Is there a documentation available for it? 

Thanks,
Harry

**Comment by dkmstr** [comment]
Use transports & assign it to pool :)

**Comment by harigist** [comment]
I created a transport (with RDP - Direct) in openuds with no network assigned to it so that anyone from outside can connect to my VDI

![image](https://user-images.githubusercontent.com/35326779/48458840-f8aaab00-e7ed-11e8-9d2b-870658cdc638.png)

**NOTE** : I have two VDI's created in Ovirt using OpenUDS for which the IP is not assigned yet

Now, How can I take a Remote Desktop for this using UDS? 

Thanks and Much Appreciated

**Comment by harigist** [comment]
Hi @dkmstr ,

I created a HTML5 RDP Transport and assigned to service pool, It is assigned successfully,

As per this doc : https://www.udsenterprise.com/en/blog/2017/01/17/access-virtual-desktops-uds-enterprise-through-htm/

I read the below line which I didn't understand, After I created a transport and assigned to service pool, I moved from Dashboard to User Mode but I am not able to find the modified service

> 
_-Switch from "Dashboard" mode to "User" mode and click on the transport icon in the modified service, choose HTML5 and continue._

![image](https://user-images.githubusercontent.com/35326779/48462149-12072380-e7fd-11e8-9ef1-3fc99c65d910.png)

Could you help me here please?

**Comment by dkmstr** [comment]
First no, the IP is not correct. :)
In order to use HTML5, you should setup an Guacamole UDS tunneler, that is based on tomcat:
https://github.com/dkmstr/openuds/tree/master/guacamole-tunnel
This is tomcat based, you need to build it and put it with the configuration file on your own server.

Second, "root" user (administrator created by UDS) cannot have services on UDS. You need to create an user into an authenticator, assign it to a group, then assign a pool to this group and use this user to access services.

Hope this helps

**Comment by harigist** [comment]
Please confirm the following steps,

1) we need to build and set up the tunneler and set up the IP of the tunneler in UDS transport
2) I created an entry in authenticator, what is the use of it? 

![image](https://user-images.githubusercontent.com/35326779/48474383-738cb980-e820-11e8-8aa2-a49077c9e5c3.png)

NOW, to which group I need to assign this ? what is the workflow of it please let me know 

3) what is the use of UDS Actor?

It would be great, If you could provide the complete steps ?

**Comment by harigist** [comment]
@dkmstr 

> First no, the IP is not correct. :)
> In order to use HTML5, you should setup an Guacamole UDS tunneler, that is based on tomcat:
> https://github.com/dkmstr/openuds/tree/master/guacamole-tunnel
> This is tomcat based, you need to build it and put it with the configuration file on your own server.



what is the configuration file I need to add?
