### ISSUE TITLE
How can I use the browser to access the UDS to VDI 

### ISSUE THREAD

**Issue by harigist** [dkmstr/openuds#34]
Hi @dkmstr ,

1) Created a user
2) Created the Servcie and Service Pool
3) Created two VDI in ovirt
4) Created a Tunneler by building the Guacamole project in OpenUDS and exposed the url as http://{SAME_IP_ADDRESSS_AS_UDS_SERVER}:8080/transport/
   NOTE: If I run this, It is returning a black screen, **Is that transport.war is just enough?**  I see the real implementation of Apache Guacamole and they have few property file where they have the details about the configuration of the remote machine it is trying to connect. 

   
![image](https://user-images.githubusercontent.com/35326779/48494837-ab155900-e854-11e8-827e-523c2455fe57.png)

5) **Installed the UDS Actor and stuck as per the issue**: https://github.com/dkmstr/openuds/issues/33

6) I installed the uds client plugin in my local

7) Created a HTML5 RDP transport using the tunneler IP (**NOTE** : In my case I deployed the transport.war in the same node as UDS server) and assigned this to the service pool

**NOW when I click on the service in the user mode** It ends up with error,

![image](https://user-images.githubusercontent.com/35326779/48509086-22a7b000-e876-11e8-9f53-f12595d1c29a.png)

When I see in the Tomcat logs, I see the following error in catalina.out in Tomcat

==> catalina.out <==
15-Nov-2018 01:28:54.863 SEVERE [http-nio-8080-exec-5] org.slf4j.impl.JCLLoggerAdapter.error Creation of WebSocket tunnel to guacd failed: The UDS base URI is not defined.
15-Nov-2018 01:28:54.921 SEVERE [http-nio-8080-exec-4] org.slf4j.impl.JCLLoggerAdapter.error HTTP tunnel request failed: The UDS base URI is not defined.
15-Nov-2018 01:29:10.041 SEVERE [http-nio-8080-exec-2] org.slf4j.impl.JCLLoggerAdapter.error Creation of WebSocket tunnel to guacd failed: The UDS base URI is not defined.
15-Nov-2018 01:29:10.096 SEVERE [http-nio-8080-exec-3] org.slf4j.impl.JCLLoggerAdapter.error HTTP tunnel request failed: The UDS base URI is not defined.
15-Nov-2018 01:29:25.235 SEVERE [http-nio-8080-exec-5] org.slf4j.impl.JCLLoggerAdapter.error Creation of WebSocket tunnel to guacd failed: **The UDS base URI is not defined.**

Also following error :

172.30.63.100 - - [15/Nov/2018:01:40:22 +0530] "GET /transport/websocket-tunnel?data=tbc3c7p3mlat3sgvjmw2qv381sn8c2mhllt54mdl&exit=http://172.30.58.154:8090/&GUAC_WIDTH=2043&GUAC_HEIGHT=600&GUAC_DPI=96&GUAC_AUDIO=audio%2Fogg&GUAC_AUDIO=audio%2Fmp4&GUAC_AUDIO=audio%2Fmpeg&GUAC_AUDIO=audio%2Fwebm&GUAC_AUDIO=audio%2Fwav&GUAC_VIDEO=video%2Fogg&GUAC_VIDEO=video%2Fmp4&GUAC_VIDEO=video%2Fwebm HTTP/1.1" 101 -
**172.30.63.100 - - [15/Nov/2018:01:40:22 +0530] "POST /transport/tunnel?connect HTTP/1.1" 500** 1038

_So it is clear that the way I deploy the Tunneler is not correct, I just deployed the transport.war in tomcat and provided the http://172.30.58.154:8080 in the HTML5 RDP Tunnel URL,
Could you help me in deploying the Tunneler properly, Please provide the steps with the configuration file for it? Thanks_

**Comment by harigist** [comment]
Hi @dkmstr,

I am able to confirm it, I deployed your open guacamole project in eclipse and it reads the **uds.conf** to get the BASEURI and it failed, so what is the base URI I need to provide here? 

Please provide the same uds.conf 

```
    /**
     * Returns the base URI of the OpenUDS service. All services providing data
     * to this Guacamole integration are hosted beneath this base URI.
     *
     * @return
     *     The base URI of the OpenUDS service.
     *
     * @throws GuacamoleException
     *     If the base URI of the OpenUDS service is not defined because the
     *     tunnel.properties file could not be parsed when the web application
     *     started.
     */
    public URI getUDSBaseURI() throws GuacamoleException {

        // Explicitly fail if the configuration was not successfully read
        if (udsBaseURI == null)
            throw new GuacamoleServerException("The UDS base URI is not defined.");

        return udsBaseURI;

    } 
```

**Comment by harigist** [comment]
@dkmstr / @mike-jumper,

Could you please check this ?

**Comment by dkmstr** [comment]
Sorry, i have no time right now to review all your messages :(.
The code is provided as is, i can help you from time to time with some issue, but several people have installed it with no problem, so you should also. 

I'll be out for a couple of weeks.
If you need running this, use the free version provided on "https://www.udsenterprise.com",

**Comment by harigist** [comment]
@dkmstr,
Sorry for the bug you. I appreciate your responses. 
Could you please help me for this last one, please let me know the steps to install tunneler (using guacamole)? 

Actually, I build transport.war and deployed in tomcat and pointed the IP and Port and it is scueessfully hitting to the tomcat transport, Do I need to configure any guacamole server as additional?
