### ISSUE TITLE
From firefox v64 automatic redirection does not work

### ISSUE THREAD

**Issue by danitorregrosa** [dkmstr/openuds#38]
Hi!

From Firefox v64 browser redirection to download url when the plugin is not installed does not work.

I have been tracking the issue and the affected code is in the function launchMozilla in https://github.com/dkmstr/openuds/blob/v2.2/server/src/uds/static/js/uds-client.coffee

It catches the NS_ERROR_UNKNOWN_PROTOCOL exception but "Firefox 64 and later will no longer raise an exception to better protect user privacy". (More info: https://www.fxsitecompat.com/en-CA/docs/2018/loading-unknown-protocol-no-longer-raises-exception/)

As a workaround I did a fast test replacing launchMozilla with launchSafari and launchIE, and both of them seem to work.

UDS version: 2.2

**Comment by dkmstr** [comment]
Hi, sorry, didn't notice your message!.

Thanks for the notice, we are removing this "check" from UDS 3.0, because it was a "bit trickt" as you have seen :).

Again, sorry for the delay, we will have this into consideration meanwhile 3.0 comes to scene ;-)
