### ISSUE TITLE
Unable to create service on xcp-ng provider.

### ISSUE THREAD

**Issue by ahleao** [dkmstr/openuds#40]
Hi,

I installed OpenUDS v2.2 on Debian 9 with Django v1.9.9 and Python v2.7.13. My provider is a XCP-ng v7.6.

After "python manage.py migrate", I started the server with:
python manage.py taskManager --start
python manage.py runserver 0.0.0.0:8000

Now, I can create the service provider (it tests ok), the Internal Auth (authenticators) and even the OS managers. But when I try to create a service on the XCP-ng service provider ("New" - "Xen Linked Clone"), the "Storage SR" select box is empty.

I know it's able to comunicate with the provider because, in the same dialog box, under the tab "Machine", I'm able to see all my VMs. It just doesn't show me the storages list.

Could you, please, help me to solve this? What could I be doing wrong?

Do I have to turn debug off and/or deploy it via Apache for this to work? Is it some missing configuration?

Thanks in advance!

**Comment by dkmstr** [comment]
Hi,
UDS can only use "shared storages" on Xen (or XCP ofc), local storages are not supported. So you don't see the storage because you don't have shared storage ;-) (Note: setup an nfs storage and you should see it)

**Comment by ahleao** [comment]
Hi,
Thanks, it worked!  :-)
Kind regards
