### ISSUE TITLE
installation doc?

### ISSUE THREAD

**Issue by villain** [dkmstr/openuds#48]
where is the installation documentation located? 

i had a look around the repository but couldn't find anything

is there a website or something i missed? i can see the project has been active for a few years, so i expect this is somewhere i'm just not seeing

**Comment by dkmstr** [comment]
Sorry, but currently that documentation is missing due to lack of time... maybe in a future will write some info. 
Again, sorry for the inconvenience

**Comment by djdejawu** [comment]
dkmstr, you will never write an installation guide. It's not interesting for you.

**Comment by Jarli01** [comment]
Not having documentation is kind of counter intuitive and FOSS, how can anyone reasonably help with the project or install this themselves? They'd just have to hammer their way thru?

**Comment by dkmstr** [comment]
If you can provide a documentation for this it will be welcome ofc.
