### ISSUE TITLE
Non-unicode characters in reports

### ISSUE THREAD

**Issue by djdejawu** [dkmstr/openuds#53]
When I'm generate users report, in the PDF file I see a squares, but not characters.
ReportLab generate PDF with WinANSI option, not unicode.
[Picture](https://ibb.co/9hpWWRn)

**Comment by dkmstr** [comment]
Hi, sorry about the inconvenience.
From 3.0 onwards, we have dropped Reportlab usage, replacing it with a much powerfull pdf generation solution. Hope this will solve your problem on next release. For now, use CVS as workaround.

**Comment by djdejawu** [comment]
So... Current stable release is 2.2.1, and I report to you a bug. Why you close my issue? And I have got fix for this.
` additional_fonts = {
        'Lato': '/usr/share/fonts/truetype/lato/Lato-Thin.ttf',
        'Lato-Bold': '/usr/share/fonts/truetype/lato/Lato-Bold.ttf',
    }
    default_style = {'fontName': 'Lato'}`
Paste it in class ListReportUsers and maybe in other classes for reports.

**Comment by dkmstr** [comment]
Sorry, closed it by mistake. :(
Can you provide a pull request for this?

**Comment by djdejawu** [comment]
Nope, you can add this lines in classes yourself.

**Comment by djdejawu** [comment]
wontfix - LOL )))
