### ISSUE TITLE
building openudsclient in thinstation enviroment

### ISSUE THREAD

**Issue by dhlfs** [dkmstr/openuds#59]
I was trying to build udsclient via this [manual](https://github.com/dkmstr/openuds/tree/master/client/thin/thinstation), but on step "5" i got this errors:
```
[root@TS_chroot]/build/packages/udsclient# . ./build.sh
Collecting paramiko
  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB 1.0 MB/s
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (2.24.0)
Requirement already satisfied: six in /usr/lib/python3.8/site-packages (1.15.0)
Collecting pycrypto
  Downloading pycrypto-2.6.1.tar.gz (446 kB)
     |████████████████████████████████| 446 kB 2.5 MB/s
Collecting pynacl>=1.0.1
  Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
     |████████████████████████████████| 961 kB 3.3 MB/s
Collecting cryptography>=2.5
  Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 3.5 MB/s
Collecting bcrypt>=3.1.3
  Downloading bcrypt-3.2.0-cp36-abi3-manylinux2010_x86_64.whl (63 kB)
     |████████████████████████████████| 63 kB 1.3 MB/s
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.8/site-packages (from requests) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests) (2020.6.20)
Collecting cffi>=1.4.1
  Downloading cffi-1.14.4-cp38-cp38-manylinux1_x86_64.whl (411 kB)
     |████████████████████████████████| 411 kB 6.9 MB/s
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 4.1 MB/s
Using legacy setup.py install for pycrypto, since package 'wheel' is not installed.
ERROR: tpm2-pkcs11-tools 1.33.7 requires pyasn1, which is not installed.
ERROR: tpm2-pkcs11-tools 1.33.7 requires pyasn1_modules, which is not installed.
Installing collected packages: pycparser, cffi, pynacl, cryptography, bcrypt, paramiko, pycrypto
    Running setup.py install for pycrypto ... done
Successfully installed bcrypt-3.2.0 cffi-1.14.4 cryptography-3.3.1 paramiko-2.7.2 pycparser-2.20 pycrypto-2.6.1 pynacl-1.4.0
cp: cannot stat '/usr/lib/python2.7/site-packages/requests*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/paramiko*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/pyasn1*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/cryptography*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/packaging*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/idna*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/asn1crypto*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/six*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/enum*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/ipaddress*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/cffi*': No such file or directory
cp: cannot stat '/usr/lib/python2.7/site-packages/Crypto*': No such file or directory
 ```
How i can fix this errors?

Full log of my commands:

1.  clone repos
```
cd /build/
 git clone --depth 1 git://github.com/Thinstation/thinstation.git
 git clone https://github.com/dkmstr/openuds.git
```
2.  ` cp -r /build/openuds/client/thin/src /build/openuds/client/thin/thinstation/udsclient/`
3.  `cp -r /build/openuds/client/thin/thinstation/udsclient/ /build/thinstation/build/packages/`
 
4.   `cd /build/thinstation`
 `./setup-chroot` 

5.   build udsclient
```
[root@TS_chroot]# cd /build/packages/udsclient
[root@TS_chroot]/build/packages/udsclient# . ./build.sh
```

**Comment by dkmstr** [comment]
This is because the thinstation client has not been ported to Python 3 (from 2.7). This support were going to be removed on 3.0, because lack of interest (no one has used it, and i don't have too much time to maintain it anyway). I forgot this removal :(.
The problem here is the Python Version probably, if you like to investigate further, ofc i can give you some support.
Basically i think that fixing the paths on "build.sh" to point to python3.x, may help.

Sorry for the inconvenience, i'll not remove this right now if someone has interest on it, but that was my idea :).

**Comment by dhlfs** [comment]
Thank you. 
I was change the `pip` command to `pip2.7` in `build.sh` and that's helped. But now i have some errors with start udsclient in thinstation.  I will continue my research and write the result.

**Comment by dhlfs** [comment]
After build i was trying to run UDSClient.py, but get the python error:
root@TS_chroot]/build/packages/udsclient/lib/UDSClient# python ./UDSClient.py
Traceback (most recent call last):
  File "./UDSClient.py", line 38, in <module>
    from uds import ui
ImportError: cannot import name 'ui' from 'uds' (/usr/lib/python3.8/site-packages/uds/__init__.py)

[root@TS_chroot]/build/packages/udsclient/lib/UDSClient# python2.7 ./UDSClient.py
Traceback (most recent call last):
  File "./UDSClient.py", line 38, in <module>
    from uds import ui
ImportError: No module named uds
``

**Comment by dkmstr** [comment]
Have you copied the "uds" folder from source? 

Look at this: https://github.com/dkmstr/openuds/tree/master/client/thin/src

The "uds" folder should be available also

**Comment by dhlfs** [comment]
> Have you copied the "uds" folder from source?
> 
> Look at this: https://github.com/dkmstr/openuds/tree/master/client/thin/src
> 
> The "uds" folder should be available also

Yes.
```
ts_566f0b9b0010:$ cd /lib/UDSClient
ts_566f0b9b0010:/lib/UDSClient$ ls -lR ./
./:
total 13
drwxr-xr-x    3 root     root           128 Jan 17 16:00 uds
-rwxr-xr-x    2 root     root          6148 Jan 17 16:00 UDSClient.py

 
./uds:
total 4
lrwxrwxrwx    1 root     root            32 Jan 17 16:00 forward.py -> ../../../full/src/uds/forward.py
lrwxrwxrwx    1 root     root            33 Jan 17 16:00 __init__.py -> ../../../full/src/uds/__init__.py
lrwxrwxrwx    1 root     root            28 Jan 17 16:00 log.py -> ../../../full/src/uds/log.py
lrwxrwxrwx    1 root     root            35 Jan 17 16:00 osDetector.py -> ../../../full/src/uds/osDetector.py
-rw-r--r--    1 root     root          3261 Jan 17 16:00 rest.py
lrwxrwxrwx    1 root     root            30 Jan 17 16:00 tools.py -> ../../../full/src/uds/tools.py
drwxr-xr-x    2 root     root            88 Jan 17 16:00 ui
 
./uds/ui:
total 12
-rw-r--r--    1 root     root          2273 Jan 17 16:00 browser.py
-rw-r--r--    1 root     root          2151 Jan 17 16:00 consoleui.py
-rw-r--r--    1 root     root          4878 Jan 17 16:00 gtkui.py
-rw-r--r--    1 root     root          1918 Jan 17 16:00 __init__.py
```
I was trying to run `UDSClient.py`  in `/lib/UDSClient` folder, but got the error:
```
ts_566f0b9b0010:/lib/UDSClient$ python2.7 UDSClient.py
Traceback (most recent call last):
  File "UDSClient.py", line 38, in <module>
    from uds import ui
ImportError: No module named uds
ts_566f0b9b0010:/lib/UDSClient$ cat /bin/udsclient
```
And i found that  file `/bin/udsclient` trying to execute  `UDSClient.pyc`, but in folder exists only `UDSClient.py` file.
Listing of `/bin/udsclient` :
```
ts_566f0b9b0010:/lib/UDSClient$ cat /bin/udsclient
#!/bin/sh
 
cd /lib/UDSClient
exec python2.7 UDSClient.pyc $@
```
What the correct extension of  that file .py or .pyc?

**Comment by dkmstr** [comment]
But the links you show are broken. I mean, do no copy the uds folder following symlins, but copying the content.
Look, 
you are here:
ts_566f0b9b0010:/lib/UDSClient$  <-- /lib/UDSClient
And the symlinks inside uds folder links to ../../../full/src/uds/...

That link is nonexisting inside the /lib/UDSClient folder. Copy the files content, not the symlinks and try again.
Also, the .pyc are the compiled version of the py. If you don't have it compiled, use the .py. The correct extension are both, but for different thins. (.py for source files, .pyc for compiled files from that source)

Hope this helps

**Comment by dhlfs** [comment]
Thanks, this was helps. Then i was get errors with the python packages, when trying to start udsclient.
And i was add in `build.sh` script command to copy all packages from "site-packages" folder. 
`rsync -avz /usr/lib/python2.7/site-packages /build/packages/udsclient/lib/python2.7/`
And now all works properly.
