### ISSUE TITLE
MS RDP on Mac could be localized and therefore have another path

### ISSUE THREAD

**Issue by chembervint** [dkmstr/openuds#66]
https://github.com/dkmstr/openuds/blob/master/server/src/uds/transports/RDP/scripts/macosx/direct.py#L12
https://github.com/dkmstr/openuds/blob/master/server/src/uds/transports/RDP/scripts/macosx/tunnel.py#L35

The path could be "/Applications/Microsoft Remote Desktop.localized/Microsoft Remote Desktop.app/Contents/MacOS/Microsoft Remote Desktop"

Macos: 12.0.1
Microsoft Remote Desktop: 10.7.2 (1965)

**Comment by dkmstr** [comment]
Hi, sorry for the delay. I'll include this as a possible path for searching it..
Thank you very much!! ;-)

**Comment by dkmstr** [comment]
Done, added for next Release.

**Comment by chembervint** [comment]
Hi, thank you!

Actually it needs one more place to be fixed: https://github.com/dkmstr/openuds/blob/master/server/src/uds/transports/RDP/scripts/macosx/direct.py#L97

here also MSrdp path is hardcoded.

**Comment by chembervint** [comment]
And for tunnel.py the same

**Comment by dkmstr** [comment]
Yes, done for both. Removed hardcoded and checked the app folder instead of the app file.
Again, thank you very much!! :)
