### ISSUE TITLE
Waiting OS indefinitely on Kali linux

### ISSUE THREAD

**Issue by ovini-ops** [dkmstr/openuds#67]
Hi people,

I have a Kali linux VM running on a Ovirt environment. When I publish the service pool, the cache VM stay on "Waiting OS" state until fail and another VM is created and the cicle repeats. A Windows 10 and a Ubuntu VM Starts normally and all actors are on version 3.5. Someone have a clue what happening in this case?

![image](https://user-images.githubusercontent.com/68972827/155208814-14b5f5d2-70b7-44f9-b1fa-49743fe62197.png)

**Comment by dkmstr** [comment]
Hi, sorry for the delay.
I'll check on Kali if i can locate the problem. Probably something related to actor running.

Sorry again,

**Comment by dkmstr** [comment]
How have you installed UDS Actor 3.5?
Because i get this problem:
 udsactor : Depends: xscreensaver but it is not installable
            Recommends: python3-prctl (>= 1.1.1) but it is not installable

The first, xscreensaver is needed because it is used to check "idle" state of users, the second is optional...

**Comment by ovini-ops** [comment]
Hi Adolfo,
I made some research here about the installation of the client on kali.
If in a fresh install you use:

sudo apt-get upgrade
sudo apt-get install xscreensaver
sudo dpkg -i udsactor_3.5.0_all.deb

Everything go fine.

If you try to install the actor before the xscreensaver, you need to run "sudo apt --fix-broken install" to fix the apt cache. With this the actor installs fine.

**Comment by dkmstr** [comment]
I'll give it a try. Thanks you!!
