### ISSUE TITLE
Several security vulnerabilities

### ISSUE THREAD

**Issue by deibit** [dkmstr/openuds#69]
Hi devs.

Any way to contact you in private, so we can address the issues without publishing the details?

Regards

**Comment by deibit** [comment]
@dkmstr Hi, Adolfo, are you available to discuss the issues?

**Comment by dkmstr** [comment]
Of course, sorry, didn't noticed the  message, last week i was on hollydays :)
Contact me if you can at dkmaster at dkmon.com please.

**Comment by dkmstr** [comment]
Fixed on 859f18883fce32715a0e8ffbea95c7af7e5f2236.
