### ISSUE TITLE
Avoid full screen Linux

### ISSUE THREAD

**Issue by a-i-m-a-r** [dkmstr/openuds#72]
When I launch UDS Client in Linux, it opens a Windows remote desktop in full screen and I cannot use any Linux windows until I close the remote session. When I launch UDS client in Windows however, it opens as a window, so I can switch back and forth between the local session and the remote session.
Is there any way I can modify a configuration file to achieve the same behaviour, i.e., open UDS Client in a window of the Linux machine.

**Comment by danitorregrosa** [comment]
Hi:

I suppose you are using RDP as transport.

If you are admin in UDS Server, you can edit the parameters for the linux tranport in Dashboard > Connectivity > Transport and then edit the transport and in the "Display" TAB modify the "Screen Size" from "Full Screen" to any other value.

If you are not admin, then you cannot modify this value. But if you are using freerdp as linux RDP client, you can exit from Full Screen Window using "Ctrl+Alt+Enter" key combination.
If you are using other linux RDP client, they may have other key combination to exit from full screen mode and you can look for it in their help.

**Comment by a-i-m-a-r** [comment]
Thank you @danitorregrosa 
"Ctrl+Alt+Enter" did the trick on xfreerdp.
