### ISSUE TITLE
Installation Debian

### ISSUE THREAD

**Issue by joaoguariglia** [dkmstr/openuds#8]
English
Hi, I did not find any tutorial that teaches you to install the tool of yours, I am following the prerequisites that you propose, but I do not know how to install, I am wanting to install in a Ubuntu 16.04, would like to pass me a tutorial step by step ?

Espanol
Hola, no he encontrado ningún tutorial que enseña a instalar la herramienta de ustedes, estoy siguiendo los requisitos previos que usted propuso, pero no sé cómo instalar, estoy queriendo instalar en un Ubuntu 16.04, tendría como pasar un tutorial paso a paso ?

**Comment by dkmstr** [comment]
Hi Joao,
Efectively, currently the documentation on "install from scratch" is a bit sparse :(.
I want to write an small introduction.
Meanwhile, you can take a look at server folder, to "requirements.txt", install theese, try to run it and i'll try to help you as much as i can.

In the process, if you like, you could write some kind of "install from scratch" instructions so everybody can be benefied ;-)
