### ISSUE TITLE
Make Tutorial

### ISSUE THREAD

**Issue by joaoguariglia** [dkmstr/openuds#9]
English

Hi, thanks for the reply.

I work with several open-source products including guacamole which I see that you also use, I can help set up a tutorial on Debian / Ubuntu, I understand that without a tutorial the project dies, it is the soul of the business, how people go To get interested in your project without a tutorial? We even have it because on youtube also how it works, if the staff does not stop, and understands your product nobody will understand what it does, luckily I like to read about open-source products, today I work for a third company Of Telefonica, and I think you should know Spain there is Comfica, good how I will do in the Debian base, I would at least understand the packages that will be used, I will mount and post in the issues of github or open a fork and I will Doing a README here, what do you think?

Espanol

Hola, gracias por la respuesta.

Yo trabajo con varios productos open-source incluyendo guacamole al que veo que ustedes también usan, puedo ayudar a montar una tutoría en Debian / Ubuntu, entiendo que sin un tutorial el proyecto muere, es el alma del negocio, como la gente va Se interesa por su proyecto sin un tutorial? Incluso tenemos que por el youtube también como funciona, si la gente no para, le y entiende su producto nadie va a entender lo que hace, por suerte me gusta leer sobre productos de código abierto, hoy trabajo para una tercera empresa De Telefónica, y creo que ustedes de España deben conocer es la Comfica, bueno como voy a hacer en la base Debian, me gustaría al menos entender los paquetes que se utilizar, voy montando y posteando en los temas del github o abro un fork y voy Haciendo un README aquí, ¿qué crees?

**Comment by dkmstr** [comment]
I think that is a fantastic idea.
I think that for an small tutorial, it should be better to add a README here, or something like that, so everybody can benefit from it.

You can see my email address on almost any source code file (anyway, it's agomez at virtualcable.es). Write me whenever you like so i can help you with this.

Thank you very much for your kindness ;-)
